name: Build and push

on:
  workflow_call:
    inputs:
      tag:
        description: 'Docker image tag'
        required: true
        type: string
    
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare docker tags
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            artnie/vlt
          tags: |
            latest
            ${{ inputs.tag }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
            context: .
            push: true
            labels: ${{ steps.meta.outputs.labels }}
            tags: ${{ steps.meta.outputs.tags }}